version: '3.4'

services:
  equationapi:
    image: ${DOCKER_REGISTRY-}equationapi
    container_name: web.equation-api
    environment:
      - VIRTUAL_HOST=equation-api.albertokato.com.br
      - PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
      - ASPNETCORE_URLS=http://+:3000
      - VIRTUAL_PORT=3000
    expose:
      - "3000"
    ports:
      - 3000:3000
    build:
      context: .
      dockerfile: EquationApi/Dockerfile
    external_links:
      - web.nginx-proxy
    working_dir: /app
    restart: always
    tty: true
networks:
  default:
    external:
      name: main
